// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Achievement struct {
	ID          string               `json:"id"`
	Name        string               `json:"name"`
	DisplayName string               `json:"displayName"`
	Description string               `json:"description"`
	Category    *AchievementCategory `json:"category"`
}

type AchievementCategory struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	DisplayName  string         `json:"displayName"`
	Achievements []*Achievement `json:"achievements"`
}

type Chill struct {
	ID              string         `json:"id"`
	Traces          []*TracePoint  `json:"traces"`
	Photo           *Photo         `json:"photo,omitempty"`
	NewAchievements []*Achievement `json:"newAchievements"`
	DistanceMeters  float64        `json:"distanceMeters"`
}

type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CoordinateInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type EndChillInput struct {
	ID             string             `json:"id"`
	TracePoints    []*TracePointInput `json:"tracePoints"`
	Photo          *PhotoInput        `json:"photo,omitempty"`
	Timestamp      string             `json:"timestamp"`
	DistanceMeters float64            `json:"distanceMeters"`
}

type Photo struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	Timestamp string `json:"timestamp"`
}

type PhotoInput struct {
	URL       string `json:"url"`
	Timestamp string `json:"timestamp"`
}

type RegisterUserInput struct {
	Name string `json:"name"`
}

type StartChillInput struct {
	Timestamp  string           `json:"timestamp"`
	Coordinate *CoordinateInput `json:"coordinate"`
}

type TracePoint struct {
	ID         string      `json:"id"`
	Timestamp  string      `json:"timestamp"`
	Coordinate *Coordinate `json:"coordinate"`
}

type TracePointInput struct {
	Timestamp  string           `json:"timestamp"`
	Coordinate *CoordinateInput `json:"coordinate"`
}

type TracePointsInput struct {
	ID          string             `json:"id"`
	TracePoints []*TracePointInput `json:"tracePoints"`
}

type UpdateUserInput struct {
	Name   *string `json:"name,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
}

type User struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Avatar       *Achievement   `json:"avatar,omitempty"`
	Chills       []*Chill       `json:"chills"`
	Achievements []*Achievement `json:"achievements"`
}
