// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	AchievementCategories string
	Achievements          string
	ChillAchievements     string
	Chills                string
	Photos                string
	TracePoints           string
	UserAchievements      string
	Users                 string
}{
	AchievementCategories: "achievement_categories",
	Achievements:          "achievements",
	ChillAchievements:     "chill_achievements",
	Chills:                "chills",
	Photos:                "photos",
	TracePoints:           "trace_points",
	UserAchievements:      "user_achievements",
	Users:                 "users",
}
