// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ChillAchievement is an object representing the database table.
type ChillAchievement struct {
	ID            string `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChillID       string `boil:"chill_id" json:"chill_id" toml:"chill_id" yaml:"chill_id"`
	AchievementID string `boil:"achievement_id" json:"achievement_id" toml:"achievement_id" yaml:"achievement_id"`

	R *chillAchievementR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chillAchievementL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChillAchievementColumns = struct {
	ID            string
	ChillID       string
	AchievementID string
}{
	ID:            "id",
	ChillID:       "chill_id",
	AchievementID: "achievement_id",
}

var ChillAchievementTableColumns = struct {
	ID            string
	ChillID       string
	AchievementID string
}{
	ID:            "chill_achievements.id",
	ChillID:       "chill_achievements.chill_id",
	AchievementID: "chill_achievements.achievement_id",
}

// Generated where

var ChillAchievementWhere = struct {
	ID            whereHelperstring
	ChillID       whereHelperstring
	AchievementID whereHelperstring
}{
	ID:            whereHelperstring{field: "\"chilly_daze\".\"chill_achievements\".\"id\""},
	ChillID:       whereHelperstring{field: "\"chilly_daze\".\"chill_achievements\".\"chill_id\""},
	AchievementID: whereHelperstring{field: "\"chilly_daze\".\"chill_achievements\".\"achievement_id\""},
}

// ChillAchievementRels is where relationship names are stored.
var ChillAchievementRels = struct {
	Achievement string
	Chill       string
}{
	Achievement: "Achievement",
	Chill:       "Chill",
}

// chillAchievementR is where relationships are stored.
type chillAchievementR struct {
	Achievement *Achievement `boil:"Achievement" json:"Achievement" toml:"Achievement" yaml:"Achievement"`
	Chill       *Chill       `boil:"Chill" json:"Chill" toml:"Chill" yaml:"Chill"`
}

// NewStruct creates a new relationship struct
func (*chillAchievementR) NewStruct() *chillAchievementR {
	return &chillAchievementR{}
}

func (r *chillAchievementR) GetAchievement() *Achievement {
	if r == nil {
		return nil
	}
	return r.Achievement
}

func (r *chillAchievementR) GetChill() *Chill {
	if r == nil {
		return nil
	}
	return r.Chill
}

// chillAchievementL is where Load methods for each relationship are stored.
type chillAchievementL struct{}

var (
	chillAchievementAllColumns            = []string{"id", "chill_id", "achievement_id"}
	chillAchievementColumnsWithoutDefault = []string{"chill_id", "achievement_id"}
	chillAchievementColumnsWithDefault    = []string{"id"}
	chillAchievementPrimaryKeyColumns     = []string{"id"}
	chillAchievementGeneratedColumns      = []string{}
)

type (
	// ChillAchievementSlice is an alias for a slice of pointers to ChillAchievement.
	// This should almost always be used instead of []ChillAchievement.
	ChillAchievementSlice []*ChillAchievement
	// ChillAchievementHook is the signature for custom ChillAchievement hook methods
	ChillAchievementHook func(context.Context, boil.ContextExecutor, *ChillAchievement) error

	chillAchievementQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chillAchievementType                 = reflect.TypeOf(&ChillAchievement{})
	chillAchievementMapping              = queries.MakeStructMapping(chillAchievementType)
	chillAchievementPrimaryKeyMapping, _ = queries.BindMapping(chillAchievementType, chillAchievementMapping, chillAchievementPrimaryKeyColumns)
	chillAchievementInsertCacheMut       sync.RWMutex
	chillAchievementInsertCache          = make(map[string]insertCache)
	chillAchievementUpdateCacheMut       sync.RWMutex
	chillAchievementUpdateCache          = make(map[string]updateCache)
	chillAchievementUpsertCacheMut       sync.RWMutex
	chillAchievementUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var chillAchievementAfterSelectHooks []ChillAchievementHook

var chillAchievementBeforeInsertHooks []ChillAchievementHook
var chillAchievementAfterInsertHooks []ChillAchievementHook

var chillAchievementBeforeUpdateHooks []ChillAchievementHook
var chillAchievementAfterUpdateHooks []ChillAchievementHook

var chillAchievementBeforeDeleteHooks []ChillAchievementHook
var chillAchievementAfterDeleteHooks []ChillAchievementHook

var chillAchievementBeforeUpsertHooks []ChillAchievementHook
var chillAchievementAfterUpsertHooks []ChillAchievementHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChillAchievement) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChillAchievement) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChillAchievement) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChillAchievement) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChillAchievement) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChillAchievement) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChillAchievement) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChillAchievement) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChillAchievement) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chillAchievementAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChillAchievementHook registers your hook function for all future operations.
func AddChillAchievementHook(hookPoint boil.HookPoint, chillAchievementHook ChillAchievementHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		chillAchievementAfterSelectHooks = append(chillAchievementAfterSelectHooks, chillAchievementHook)
	case boil.BeforeInsertHook:
		chillAchievementBeforeInsertHooks = append(chillAchievementBeforeInsertHooks, chillAchievementHook)
	case boil.AfterInsertHook:
		chillAchievementAfterInsertHooks = append(chillAchievementAfterInsertHooks, chillAchievementHook)
	case boil.BeforeUpdateHook:
		chillAchievementBeforeUpdateHooks = append(chillAchievementBeforeUpdateHooks, chillAchievementHook)
	case boil.AfterUpdateHook:
		chillAchievementAfterUpdateHooks = append(chillAchievementAfterUpdateHooks, chillAchievementHook)
	case boil.BeforeDeleteHook:
		chillAchievementBeforeDeleteHooks = append(chillAchievementBeforeDeleteHooks, chillAchievementHook)
	case boil.AfterDeleteHook:
		chillAchievementAfterDeleteHooks = append(chillAchievementAfterDeleteHooks, chillAchievementHook)
	case boil.BeforeUpsertHook:
		chillAchievementBeforeUpsertHooks = append(chillAchievementBeforeUpsertHooks, chillAchievementHook)
	case boil.AfterUpsertHook:
		chillAchievementAfterUpsertHooks = append(chillAchievementAfterUpsertHooks, chillAchievementHook)
	}
}

// One returns a single chillAchievement record from the query.
func (q chillAchievementQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChillAchievement, error) {
	o := &ChillAchievement{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for chill_achievements")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChillAchievement records from the query.
func (q chillAchievementQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChillAchievementSlice, error) {
	var o []*ChillAchievement

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to ChillAchievement slice")
	}

	if len(chillAchievementAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChillAchievement records in the query.
func (q chillAchievementQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count chill_achievements rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chillAchievementQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if chill_achievements exists")
	}

	return count > 0, nil
}

// Achievement pointed to by the foreign key.
func (o *ChillAchievement) Achievement(mods ...qm.QueryMod) achievementQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AchievementID),
	}

	queryMods = append(queryMods, mods...)

	return Achievements(queryMods...)
}

// Chill pointed to by the foreign key.
func (o *ChillAchievement) Chill(mods ...qm.QueryMod) chillQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChillID),
	}

	queryMods = append(queryMods, mods...)

	return Chills(queryMods...)
}

// LoadAchievement allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chillAchievementL) LoadAchievement(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChillAchievement interface{}, mods queries.Applicator) error {
	var slice []*ChillAchievement
	var object *ChillAchievement

	if singular {
		var ok bool
		object, ok = maybeChillAchievement.(*ChillAchievement)
		if !ok {
			object = new(ChillAchievement)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChillAchievement)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChillAchievement))
			}
		}
	} else {
		s, ok := maybeChillAchievement.(*[]*ChillAchievement)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChillAchievement)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChillAchievement))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &chillAchievementR{}
		}
		args = append(args, object.AchievementID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chillAchievementR{}
			}

			for _, a := range args {
				if a == obj.AchievementID {
					continue Outer
				}
			}

			args = append(args, obj.AchievementID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`chilly_daze.achievements`),
		qm.WhereIn(`chilly_daze.achievements.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Achievement")
	}

	var resultSlice []*Achievement
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Achievement")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for achievements")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for achievements")
	}

	if len(achievementAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Achievement = foreign
		if foreign.R == nil {
			foreign.R = &achievementR{}
		}
		foreign.R.ChillAchievements = append(foreign.R.ChillAchievements, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AchievementID == foreign.ID {
				local.R.Achievement = foreign
				if foreign.R == nil {
					foreign.R = &achievementR{}
				}
				foreign.R.ChillAchievements = append(foreign.R.ChillAchievements, local)
				break
			}
		}
	}

	return nil
}

// LoadChill allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chillAchievementL) LoadChill(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChillAchievement interface{}, mods queries.Applicator) error {
	var slice []*ChillAchievement
	var object *ChillAchievement

	if singular {
		var ok bool
		object, ok = maybeChillAchievement.(*ChillAchievement)
		if !ok {
			object = new(ChillAchievement)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChillAchievement)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChillAchievement))
			}
		}
	} else {
		s, ok := maybeChillAchievement.(*[]*ChillAchievement)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChillAchievement)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChillAchievement))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &chillAchievementR{}
		}
		args = append(args, object.ChillID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chillAchievementR{}
			}

			for _, a := range args {
				if a == obj.ChillID {
					continue Outer
				}
			}

			args = append(args, obj.ChillID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`chilly_daze.chills`),
		qm.WhereIn(`chilly_daze.chills.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Chill")
	}

	var resultSlice []*Chill
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Chill")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chills")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chills")
	}

	if len(chillAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Chill = foreign
		if foreign.R == nil {
			foreign.R = &chillR{}
		}
		foreign.R.ChillAchievements = append(foreign.R.ChillAchievements, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChillID == foreign.ID {
				local.R.Chill = foreign
				if foreign.R == nil {
					foreign.R = &chillR{}
				}
				foreign.R.ChillAchievements = append(foreign.R.ChillAchievements, local)
				break
			}
		}
	}

	return nil
}

// SetAchievement of the chillAchievement to the related item.
// Sets o.R.Achievement to related.
// Adds o to related.R.ChillAchievements.
func (o *ChillAchievement) SetAchievement(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Achievement) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chilly_daze\".\"chill_achievements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"achievement_id"}),
		strmangle.WhereClause("\"", "\"", 2, chillAchievementPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AchievementID = related.ID
	if o.R == nil {
		o.R = &chillAchievementR{
			Achievement: related,
		}
	} else {
		o.R.Achievement = related
	}

	if related.R == nil {
		related.R = &achievementR{
			ChillAchievements: ChillAchievementSlice{o},
		}
	} else {
		related.R.ChillAchievements = append(related.R.ChillAchievements, o)
	}

	return nil
}

// SetChill of the chillAchievement to the related item.
// Sets o.R.Chill to related.
// Adds o to related.R.ChillAchievements.
func (o *ChillAchievement) SetChill(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Chill) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chilly_daze\".\"chill_achievements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"chill_id"}),
		strmangle.WhereClause("\"", "\"", 2, chillAchievementPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChillID = related.ID
	if o.R == nil {
		o.R = &chillAchievementR{
			Chill: related,
		}
	} else {
		o.R.Chill = related
	}

	if related.R == nil {
		related.R = &chillR{
			ChillAchievements: ChillAchievementSlice{o},
		}
	} else {
		related.R.ChillAchievements = append(related.R.ChillAchievements, o)
	}

	return nil
}

// ChillAchievements retrieves all the records using an executor.
func ChillAchievements(mods ...qm.QueryMod) chillAchievementQuery {
	mods = append(mods, qm.From("\"chilly_daze\".\"chill_achievements\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"chilly_daze\".\"chill_achievements\".*"})
	}

	return chillAchievementQuery{q}
}

// FindChillAchievement retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChillAchievement(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ChillAchievement, error) {
	chillAchievementObj := &ChillAchievement{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chilly_daze\".\"chill_achievements\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, chillAchievementObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from chill_achievements")
	}

	if err = chillAchievementObj.doAfterSelectHooks(ctx, exec); err != nil {
		return chillAchievementObj, err
	}

	return chillAchievementObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChillAchievement) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no chill_achievements provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chillAchievementColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chillAchievementInsertCacheMut.RLock()
	cache, cached := chillAchievementInsertCache[key]
	chillAchievementInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chillAchievementAllColumns,
			chillAchievementColumnsWithDefault,
			chillAchievementColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chillAchievementType, chillAchievementMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chillAchievementType, chillAchievementMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chilly_daze\".\"chill_achievements\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chilly_daze\".\"chill_achievements\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into chill_achievements")
	}

	if !cached {
		chillAchievementInsertCacheMut.Lock()
		chillAchievementInsertCache[key] = cache
		chillAchievementInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChillAchievement.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChillAchievement) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	chillAchievementUpdateCacheMut.RLock()
	cache, cached := chillAchievementUpdateCache[key]
	chillAchievementUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chillAchievementAllColumns,
			chillAchievementPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update chill_achievements, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chilly_daze\".\"chill_achievements\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chillAchievementPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chillAchievementType, chillAchievementMapping, append(wl, chillAchievementPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update chill_achievements row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for chill_achievements")
	}

	if !cached {
		chillAchievementUpdateCacheMut.Lock()
		chillAchievementUpdateCache[key] = cache
		chillAchievementUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q chillAchievementQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for chill_achievements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for chill_achievements")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChillAchievementSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chillAchievementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chilly_daze\".\"chill_achievements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chillAchievementPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in chillAchievement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all chillAchievement")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChillAchievement) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no chill_achievements provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chillAchievementColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chillAchievementUpsertCacheMut.RLock()
	cache, cached := chillAchievementUpsertCache[key]
	chillAchievementUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			chillAchievementAllColumns,
			chillAchievementColumnsWithDefault,
			chillAchievementColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chillAchievementAllColumns,
			chillAchievementPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert chill_achievements, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(chillAchievementPrimaryKeyColumns))
			copy(conflict, chillAchievementPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chilly_daze\".\"chill_achievements\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(chillAchievementType, chillAchievementMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chillAchievementType, chillAchievementMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert chill_achievements")
	}

	if !cached {
		chillAchievementUpsertCacheMut.Lock()
		chillAchievementUpsertCache[key] = cache
		chillAchievementUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChillAchievement record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChillAchievement) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no ChillAchievement provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chillAchievementPrimaryKeyMapping)
	sql := "DELETE FROM \"chilly_daze\".\"chill_achievements\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from chill_achievements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for chill_achievements")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chillAchievementQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no chillAchievementQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from chill_achievements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for chill_achievements")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChillAchievementSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(chillAchievementBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chillAchievementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chilly_daze\".\"chill_achievements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chillAchievementPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from chillAchievement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for chill_achievements")
	}

	if len(chillAchievementAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChillAchievement) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChillAchievement(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChillAchievementSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChillAchievementSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chillAchievementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chilly_daze\".\"chill_achievements\".* FROM \"chilly_daze\".\"chill_achievements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chillAchievementPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in ChillAchievementSlice")
	}

	*o = slice

	return nil
}

// ChillAchievementExists checks if the ChillAchievement row exists.
func ChillAchievementExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chilly_daze\".\"chill_achievements\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if chill_achievements exists")
	}

	return exists, nil
}

// Exists checks if the ChillAchievement row exists.
func (o *ChillAchievement) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChillAchievementExists(ctx, exec, o.ID)
}
