// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Photo is an object representing the database table.
type Photo struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChillID   string    `boil:"chill_id" json:"chill_id" toml:"chill_id" yaml:"chill_id"`
	Timestamp time.Time `boil:"timestamp" json:"timestamp" toml:"timestamp" yaml:"timestamp"`
	URL       string    `boil:"url" json:"url" toml:"url" yaml:"url"`

	R *photoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L photoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PhotoColumns = struct {
	ID        string
	ChillID   string
	Timestamp string
	URL       string
}{
	ID:        "id",
	ChillID:   "chill_id",
	Timestamp: "timestamp",
	URL:       "url",
}

var PhotoTableColumns = struct {
	ID        string
	ChillID   string
	Timestamp string
	URL       string
}{
	ID:        "photos.id",
	ChillID:   "photos.chill_id",
	Timestamp: "photos.timestamp",
	URL:       "photos.url",
}

// Generated where

var PhotoWhere = struct {
	ID        whereHelperstring
	ChillID   whereHelperstring
	Timestamp whereHelpertime_Time
	URL       whereHelperstring
}{
	ID:        whereHelperstring{field: "\"chilly_daze\".\"photos\".\"id\""},
	ChillID:   whereHelperstring{field: "\"chilly_daze\".\"photos\".\"chill_id\""},
	Timestamp: whereHelpertime_Time{field: "\"chilly_daze\".\"photos\".\"timestamp\""},
	URL:       whereHelperstring{field: "\"chilly_daze\".\"photos\".\"url\""},
}

// PhotoRels is where relationship names are stored.
var PhotoRels = struct {
	Chill string
}{
	Chill: "Chill",
}

// photoR is where relationships are stored.
type photoR struct {
	Chill *Chill `boil:"Chill" json:"Chill" toml:"Chill" yaml:"Chill"`
}

// NewStruct creates a new relationship struct
func (*photoR) NewStruct() *photoR {
	return &photoR{}
}

func (r *photoR) GetChill() *Chill {
	if r == nil {
		return nil
	}
	return r.Chill
}

// photoL is where Load methods for each relationship are stored.
type photoL struct{}

var (
	photoAllColumns            = []string{"id", "chill_id", "timestamp", "url"}
	photoColumnsWithoutDefault = []string{"chill_id", "url"}
	photoColumnsWithDefault    = []string{"id", "timestamp"}
	photoPrimaryKeyColumns     = []string{"id"}
	photoGeneratedColumns      = []string{}
)

type (
	// PhotoSlice is an alias for a slice of pointers to Photo.
	// This should almost always be used instead of []Photo.
	PhotoSlice []*Photo
	// PhotoHook is the signature for custom Photo hook methods
	PhotoHook func(context.Context, boil.ContextExecutor, *Photo) error

	photoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	photoType                 = reflect.TypeOf(&Photo{})
	photoMapping              = queries.MakeStructMapping(photoType)
	photoPrimaryKeyMapping, _ = queries.BindMapping(photoType, photoMapping, photoPrimaryKeyColumns)
	photoInsertCacheMut       sync.RWMutex
	photoInsertCache          = make(map[string]insertCache)
	photoUpdateCacheMut       sync.RWMutex
	photoUpdateCache          = make(map[string]updateCache)
	photoUpsertCacheMut       sync.RWMutex
	photoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var photoAfterSelectHooks []PhotoHook

var photoBeforeInsertHooks []PhotoHook
var photoAfterInsertHooks []PhotoHook

var photoBeforeUpdateHooks []PhotoHook
var photoAfterUpdateHooks []PhotoHook

var photoBeforeDeleteHooks []PhotoHook
var photoAfterDeleteHooks []PhotoHook

var photoBeforeUpsertHooks []PhotoHook
var photoAfterUpsertHooks []PhotoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Photo) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Photo) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Photo) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Photo) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Photo) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Photo) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Photo) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Photo) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Photo) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPhotoHook registers your hook function for all future operations.
func AddPhotoHook(hookPoint boil.HookPoint, photoHook PhotoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		photoAfterSelectHooks = append(photoAfterSelectHooks, photoHook)
	case boil.BeforeInsertHook:
		photoBeforeInsertHooks = append(photoBeforeInsertHooks, photoHook)
	case boil.AfterInsertHook:
		photoAfterInsertHooks = append(photoAfterInsertHooks, photoHook)
	case boil.BeforeUpdateHook:
		photoBeforeUpdateHooks = append(photoBeforeUpdateHooks, photoHook)
	case boil.AfterUpdateHook:
		photoAfterUpdateHooks = append(photoAfterUpdateHooks, photoHook)
	case boil.BeforeDeleteHook:
		photoBeforeDeleteHooks = append(photoBeforeDeleteHooks, photoHook)
	case boil.AfterDeleteHook:
		photoAfterDeleteHooks = append(photoAfterDeleteHooks, photoHook)
	case boil.BeforeUpsertHook:
		photoBeforeUpsertHooks = append(photoBeforeUpsertHooks, photoHook)
	case boil.AfterUpsertHook:
		photoAfterUpsertHooks = append(photoAfterUpsertHooks, photoHook)
	}
}

// One returns a single photo record from the query.
func (q photoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Photo, error) {
	o := &Photo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for photos")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Photo records from the query.
func (q photoQuery) All(ctx context.Context, exec boil.ContextExecutor) (PhotoSlice, error) {
	var o []*Photo

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to Photo slice")
	}

	if len(photoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Photo records in the query.
func (q photoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count photos rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q photoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if photos exists")
	}

	return count > 0, nil
}

// Chill pointed to by the foreign key.
func (o *Photo) Chill(mods ...qm.QueryMod) chillQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChillID),
	}

	queryMods = append(queryMods, mods...)

	return Chills(queryMods...)
}

// LoadChill allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (photoL) LoadChill(ctx context.Context, e boil.ContextExecutor, singular bool, maybePhoto interface{}, mods queries.Applicator) error {
	var slice []*Photo
	var object *Photo

	if singular {
		var ok bool
		object, ok = maybePhoto.(*Photo)
		if !ok {
			object = new(Photo)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePhoto))
			}
		}
	} else {
		s, ok := maybePhoto.(*[]*Photo)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePhoto))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &photoR{}
		}
		args = append(args, object.ChillID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &photoR{}
			}

			for _, a := range args {
				if a == obj.ChillID {
					continue Outer
				}
			}

			args = append(args, obj.ChillID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`chilly_daze.chills`),
		qm.WhereIn(`chilly_daze.chills.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Chill")
	}

	var resultSlice []*Chill
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Chill")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chills")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chills")
	}

	if len(chillAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Chill = foreign
		if foreign.R == nil {
			foreign.R = &chillR{}
		}
		foreign.R.Photos = append(foreign.R.Photos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChillID == foreign.ID {
				local.R.Chill = foreign
				if foreign.R == nil {
					foreign.R = &chillR{}
				}
				foreign.R.Photos = append(foreign.R.Photos, local)
				break
			}
		}
	}

	return nil
}

// SetChill of the photo to the related item.
// Sets o.R.Chill to related.
// Adds o to related.R.Photos.
func (o *Photo) SetChill(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Chill) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chilly_daze\".\"photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"chill_id"}),
		strmangle.WhereClause("\"", "\"", 2, photoPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChillID = related.ID
	if o.R == nil {
		o.R = &photoR{
			Chill: related,
		}
	} else {
		o.R.Chill = related
	}

	if related.R == nil {
		related.R = &chillR{
			Photos: PhotoSlice{o},
		}
	} else {
		related.R.Photos = append(related.R.Photos, o)
	}

	return nil
}

// Photos retrieves all the records using an executor.
func Photos(mods ...qm.QueryMod) photoQuery {
	mods = append(mods, qm.From("\"chilly_daze\".\"photos\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"chilly_daze\".\"photos\".*"})
	}

	return photoQuery{q}
}

// FindPhoto retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPhoto(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Photo, error) {
	photoObj := &Photo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chilly_daze\".\"photos\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, photoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from photos")
	}

	if err = photoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return photoObj, err
	}

	return photoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Photo) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no photos provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(photoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	photoInsertCacheMut.RLock()
	cache, cached := photoInsertCache[key]
	photoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			photoAllColumns,
			photoColumnsWithDefault,
			photoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(photoType, photoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chilly_daze\".\"photos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chilly_daze\".\"photos\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into photos")
	}

	if !cached {
		photoInsertCacheMut.Lock()
		photoInsertCache[key] = cache
		photoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Photo.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Photo) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	photoUpdateCacheMut.RLock()
	cache, cached := photoUpdateCache[key]
	photoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			photoAllColumns,
			photoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update photos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chilly_daze\".\"photos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, photoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, append(wl, photoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update photos row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for photos")
	}

	if !cached {
		photoUpdateCacheMut.Lock()
		photoUpdateCache[key] = cache
		photoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q photoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for photos")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PhotoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chilly_daze\".\"photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, photoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in photo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all photo")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Photo) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no photos provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(photoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	photoUpsertCacheMut.RLock()
	cache, cached := photoUpsertCache[key]
	photoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			photoAllColumns,
			photoColumnsWithDefault,
			photoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			photoAllColumns,
			photoPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert photos, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(photoPrimaryKeyColumns))
			copy(conflict, photoPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chilly_daze\".\"photos\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(photoType, photoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert photos")
	}

	if !cached {
		photoUpsertCacheMut.Lock()
		photoUpsertCache[key] = cache
		photoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Photo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Photo) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no Photo provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), photoPrimaryKeyMapping)
	sql := "DELETE FROM \"chilly_daze\".\"photos\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for photos")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q photoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no photoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for photos")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PhotoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(photoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chilly_daze\".\"photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, photoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from photo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for photos")
	}

	if len(photoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Photo) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPhoto(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PhotoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PhotoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chilly_daze\".\"photos\".* FROM \"chilly_daze\".\"photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, photoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in PhotoSlice")
	}

	*o = slice

	return nil
}

// PhotoExists checks if the Photo row exists.
func PhotoExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chilly_daze\".\"photos\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if photos exists")
	}

	return exists, nil
}

// Exists checks if the Photo row exists.
func (o *Photo) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PhotoExists(ctx, exec, o.ID)
}
